development:
  adapter: postgresql
  encoding: unicode
  database: to_watch_development
  pool: 5
  username: postgres
  password: 
  host: localhost
  port: 1234

test:
  adapter: postgresql
  encoding: unicode
  database: to_watch_test
  pool: 5
  username: postgres
  password: 
  host: localhost
  port: 1234

production:
  adapter: postgresql
  encoding: unicode
  database: to_watch_production
  pool: 5
  username: fsi
  password: fsi12
